version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel_app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/vendor
    ports:
      - "8080:8080"
    networks:
      - common-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel_payment_system
      MYSQL_ROOT_PASSWORD: Root@3456
      MYSQL_PASSWORD: Sql@3456
      MYSQL_USER: sqluser
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - common-network

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - common-network
    ports:
      - "8081:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - common-network

networks:
  common-network:
    external: true

volumes:
  dbdata:
    driver: local
